apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: es-client
  labels:
    application: demo
    component: elasticsearch
    type: client
spec:
  replicas: 2
  minReadySeconds: 5
  strategy:
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        application: demo
        component: elasticsearch
        type: client
    spec:
      containers:
      - name: elasticsearch
        image: quay.io/pires/docker-elasticsearch-kubernetes:2.4.1
        imagePullPolicy: Always
        ports:
        - containerPort: 9300
          name: transport
        - containerPort: 9200
          name: http
        readinessProbe:
          httpGet:
            path: /
            port: 9200
        env:
        - name: DISCOVERY_SERVICE
          value: elasticsearch-masters
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CLUSTER_NAME
          value: 'demo'
        - name: NODE_MASTER
          value: 'false'
        - name: NODE_DATA
          value: 'false'
        - name: ES_HEAP_SIZE
          value: '1g'
        securityContext:
          privileged: true
          capabilities:
            add:
              - IPC_LOCK
        resources:
          requests:
            memory: 2Gi
