apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: es-master
  labels:
    application: demo
    component: elasticsearch
    type: master
spec:
  replicas: 3
  minReadySeconds: 5
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        application: demo
        component: elasticsearch
        type: master
    spec:
      containers:
      - name: elasticsearch
        image: quay.io/pires/docker-elasticsearch-kubernetes:2.4.1
        imagePullPolicy: Always
        ports:
        - containerPort: 9300
          name: transport
        env:
        - name: DISCOVERY_SERVICE
          value: elasticsearch-masters
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CLUSTER_NAME
          value: 'demo'
        - name: NODE_MASTER
          value: 'true'
        - name: NODE_DATA
          value: 'false'
        - name: ES_HEAP_SIZE
          value: '1g'
        securityContext:
          privileged: true
          capabilities:
            add:
              - IPC_LOCK
        resources:
          requests:
            memory: 2Gi
